// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6jqZUpHCiSoypwZyIpt0zpl7uyOdpDwc',
    appId: '1:598041253528:web:5fae8be8ee2f5172bca2ed',
    messagingSenderId: '598041253528',
    projectId: 'nowhere-8985a',
    authDomain: 'nowhere-8985a.firebaseapp.com',
    storageBucket: 'nowhere-8985a.firebasestorage.app',
    measurementId: 'G-34NCEGPGG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpK019Nc1VcBmPo1ryRvNdxQLAuhcOcXI',
    appId: '1:598041253528:android:790893fed648925bbca2ed',
    messagingSenderId: '598041253528',
    projectId: 'nowhere-8985a',
    storageBucket: 'nowhere-8985a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnT4VEHYzTJzlxDItf3rpwKp9GMYBv-DQ',
    appId: '1:598041253528:ios:a246dd7cfe692138bca2ed',
    messagingSenderId: '598041253528',
    projectId: 'nowhere-8985a',
    storageBucket: 'nowhere-8985a.firebasestorage.app',
    iosBundleId: 'com.example.nowHere',
  );
}
